name: Build, Analyze, and Push DBWriter Service to ECR

on:
  workflow_dispatch:
    inputs:
      force_cleanup:
        description: 'Force ECR cleanup even if no changes'
        required: false
        default: true
        type: boolean

jobs:
  build_test_scan_push:
    name: Build, Analyze, and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verify Compiled Classes Exist
        run: |
          echo "Checking for compiled Java classes in target/classes..."
          ls -l target/classes || echo "WARNING: target/classes directory is missing!"
          find target/classes -name "*.class" > /dev/null 2>&1
          if [ $? -ne 0 ]; then
            echo "WARNING: No compiled class files found!"
          else
            echo "INFO: Compiled class files found."
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push DBWriter Image to ECR
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          SHORT_SHA=${GITHUB_SHA:0:7}
          BUILD_NUMBER=${GITHUB_RUN_NUMBER}
          IMAGE_TAG="v1.0.${BUILD_NUMBER}"

          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=${{ secrets.ECR_REPO_DBWRITER }}

          echo "🏗️ Building image: $IMAGE_TAG"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./Dockerfile .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Clean up old ECR images (keep only last 2)
        if: success() && github.event.inputs.force_cleanup == 'true'
        run: |
          ECR_REPOSITORY=${{ secrets.ECR_REPO_DBWRITER }}
          echo "🧹 Cleaning up old images in $ECR_REPOSITORY..."

          TOTAL_IMAGES=$(aws ecr describe-images \
            --repository-name $ECR_REPOSITORY \
            --query 'length(imageDetails)' \
            --output text)

          if [ "$TOTAL_IMAGES" -gt 2 ]; then
            IMAGES_TO_DELETE=$(aws ecr describe-images \
              --repository-name $ECR_REPOSITORY \
              --query 'sort_by(imageDetails,& imagePushedAt)[:-2].[imageDigest]' \
              --output text)

            echo "$IMAGES_TO_DELETE" | while read -r digest; do
              if [ ! -z "$digest" ]; then
                aws ecr batch-delete-image \
                  --repository-name $ECR_REPOSITORY \
                  --image-ids imageDigest=$digest
                echo "✅ Deleted image: ${digest:0:12}"
              fi
            done
          else
            echo "✅ No cleanup needed"
          fi

      - name: Show Remaining Images and Cost Summary
        if: success()
        run: |
          ECR_REPOSITORY=${{ secrets.ECR_REPO_DBWRITER }}
          aws ecr describe-images \
            --repository-name $ECR_REPOSITORY \
            --query 'imageDetails[*].[imageTags[0],imageSizeInBytes,imagePushedAt]' \
            --output table

          TOTAL_SIZE=$(aws ecr describe-images \
            --repository-name $ECR_REPOSITORY \
            --query 'sum(imageDetails[].imageSizeInBytes)' \
            --output text)

          if [ "$TOTAL_SIZE" != "None" ] && [ "$TOTAL_SIZE" != "0" ]; then
            TOTAL_GB=$(echo "scale=3; $TOTAL_SIZE / 1024 / 1024 / 1024" | bc -l)
            MONTHLY_COST=$(echo "scale=2; $TOTAL_GB * 0.10" | bc -l)
            echo "💰 Storage: ${TOTAL_GB} GB"
            echo "💵 Estimated monthly cost: \$${MONTHLY_COST}"
          else
            echo "📊 Repository is empty"
          fi
